// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/nauthz.proto

// Nostr Authorization Services

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A permit or deny decision
type Decision int32

const (
	Decision_DECISION_UNSPECIFIED Decision = 0
	Decision_DECISION_PERMIT      Decision = 1
	Decision_DECISION_DENY        Decision = 2
)

// Enum value maps for Decision.
var (
	Decision_name = map[int32]string{
		0: "DECISION_UNSPECIFIED",
		1: "DECISION_PERMIT",
		2: "DECISION_DENY",
	}
	Decision_value = map[string]int32{
		"DECISION_UNSPECIFIED": 0,
		"DECISION_PERMIT":      1,
		"DECISION_DENY":        2,
	}
)

func (x Decision) Enum() *Decision {
	p := new(Decision)
	*p = x
	return p
}

func (x Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_nauthz_proto_enumTypes[0].Descriptor()
}

func (Decision) Type() protoreflect.EnumType {
	return &file_proto_nauthz_proto_enumTypes[0]
}

func (x Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Decision.Descriptor instead.
func (Decision) EnumDescriptor() ([]byte, []int) {
	return file_proto_nauthz_proto_rawDescGZIP(), []int{0}
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                  // 32-byte SHA256 hash of serialized event
	Pubkey        []byte                 `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`                          // 32-byte public key of event creator
	CreatedAt     uint64                 `protobuf:"fixed64,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // UNIX timestamp provided by event creator
	Kind          uint64                 `protobuf:"varint,4,opt,name=kind,proto3" json:"kind,omitempty"`                             // event kind
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                        // arbitrary event contents
	Tags          []*Event_TagEntry      `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`                              // event tag array
	Sig           []byte                 `protobuf:"bytes,7,opt,name=sig,proto3" json:"sig,omitempty"`                                // 32-byte signature of the event id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_nauthz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nauthz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_nauthz_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Event) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *Event) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Event) GetKind() uint64 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *Event) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Event) GetTags() []*Event_TagEntry {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Event) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

// Event data and metadata for authorization decisions
type EventRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Event         *Event                  `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	IpAddr        *string                 `protobuf:"bytes,2,opt,name=ip_addr,json=ipAddr,proto3,oneof" json:"ip_addr,omitempty"`
	Origin        *string                 `protobuf:"bytes,3,opt,name=origin,proto3,oneof" json:"origin,omitempty"`
	UserAgent     *string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3,oneof" json:"user_agent,omitempty"`
	AuthPubkey    []byte                  `protobuf:"bytes,5,opt,name=auth_pubkey,json=authPubkey,proto3,oneof" json:"auth_pubkey,omitempty"`
	Nip05         *EventRequest_Nip05Name `protobuf:"bytes,6,opt,name=nip05,proto3,oneof" json:"nip05,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRequest) Reset() {
	*x = EventRequest{}
	mi := &file_proto_nauthz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequest) ProtoMessage() {}

func (x *EventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nauthz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequest.ProtoReflect.Descriptor instead.
func (*EventRequest) Descriptor() ([]byte, []int) {
	return file_proto_nauthz_proto_rawDescGZIP(), []int{1}
}

func (x *EventRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EventRequest) GetIpAddr() string {
	if x != nil && x.IpAddr != nil {
		return *x.IpAddr
	}
	return ""
}

func (x *EventRequest) GetOrigin() string {
	if x != nil && x.Origin != nil {
		return *x.Origin
	}
	return ""
}

func (x *EventRequest) GetUserAgent() string {
	if x != nil && x.UserAgent != nil {
		return *x.UserAgent
	}
	return ""
}

func (x *EventRequest) GetAuthPubkey() []byte {
	if x != nil {
		return x.AuthPubkey
	}
	return nil
}

func (x *EventRequest) GetNip05() *EventRequest_Nip05Name {
	if x != nil {
		return x.Nip05
	}
	return nil
}

// Response to a event authorization request
type EventReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      Decision               `protobuf:"varint,1,opt,name=decision,proto3,enum=nauthz.Decision" json:"decision,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventReply) Reset() {
	*x = EventReply{}
	mi := &file_proto_nauthz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventReply) ProtoMessage() {}

func (x *EventReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nauthz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventReply.ProtoReflect.Descriptor instead.
func (*EventReply) Descriptor() ([]byte, []int) {
	return file_proto_nauthz_proto_rawDescGZIP(), []int{2}
}

func (x *EventReply) GetDecision() Decision {
	if x != nil {
		return x.Decision
	}
	return Decision_DECISION_UNSPECIFIED
}

func (x *EventReply) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

// Individual values for a single tag
type Event_TagEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_TagEntry) Reset() {
	*x = Event_TagEntry{}
	mi := &file_proto_nauthz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_TagEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_TagEntry) ProtoMessage() {}

func (x *Event_TagEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nauthz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_TagEntry.ProtoReflect.Descriptor instead.
func (*Event_TagEntry) Descriptor() ([]byte, []int) {
	return file_proto_nauthz_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Event_TagEntry) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type EventRequest_Nip05Name struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Local         string                 `protobuf:"bytes,1,opt,name=local,proto3" json:"local,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRequest_Nip05Name) Reset() {
	*x = EventRequest_Nip05Name{}
	mi := &file_proto_nauthz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRequest_Nip05Name) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequest_Nip05Name) ProtoMessage() {}

func (x *EventRequest_Nip05Name) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nauthz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequest_Nip05Name.ProtoReflect.Descriptor instead.
func (*EventRequest_Nip05Name) Descriptor() ([]byte, []int) {
	return file_proto_nauthz_proto_rawDescGZIP(), []int{1, 0}
}

func (x *EventRequest_Nip05Name) GetLocal() string {
	if x != nil {
		return x.Local
	}
	return ""
}

func (x *EventRequest_Nip05Name) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

var File_proto_nauthz_proto protoreflect.FileDescriptor

const file_proto_nauthz_proto_rawDesc = "" +
	"\n" +
	"\x12proto/nauthz.proto\x12\x06nauthz\"\xde\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x16\n" +
	"\x06pubkey\x18\x02 \x01(\fR\x06pubkey\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x06R\tcreatedAt\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\x04R\x04kind\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12*\n" +
	"\x04tags\x18\x06 \x03(\v2\x16.nauthz.Event.TagEntryR\x04tags\x12\x10\n" +
	"\x03sig\x18\a \x01(\fR\x03sig\x1a\"\n" +
	"\bTagEntry\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xee\x02\n" +
	"\fEventRequest\x12#\n" +
	"\x05event\x18\x01 \x01(\v2\r.nauthz.EventR\x05event\x12\x1c\n" +
	"\aip_addr\x18\x02 \x01(\tH\x00R\x06ipAddr\x88\x01\x01\x12\x1b\n" +
	"\x06origin\x18\x03 \x01(\tH\x01R\x06origin\x88\x01\x01\x12\"\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tH\x02R\tuserAgent\x88\x01\x01\x12$\n" +
	"\vauth_pubkey\x18\x05 \x01(\fH\x03R\n" +
	"authPubkey\x88\x01\x01\x129\n" +
	"\x05nip05\x18\x06 \x01(\v2\x1e.nauthz.EventRequest.Nip05NameH\x04R\x05nip05\x88\x01\x01\x1a9\n" +
	"\tNip05Name\x12\x14\n" +
	"\x05local\x18\x01 \x01(\tR\x05local\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domainB\n" +
	"\n" +
	"\b_ip_addrB\t\n" +
	"\a_originB\r\n" +
	"\v_user_agentB\x0e\n" +
	"\f_auth_pubkeyB\b\n" +
	"\x06_nip05\"e\n" +
	"\n" +
	"EventReply\x12,\n" +
	"\bdecision\x18\x01 \x01(\x0e2\x10.nauthz.DecisionR\bdecision\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message*L\n" +
	"\bDecision\x12\x18\n" +
	"\x14DECISION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fDECISION_PERMIT\x10\x01\x12\x11\n" +
	"\rDECISION_DENY\x10\x022I\n" +
	"\rAuthorization\x128\n" +
	"\n" +
	"EventAdmit\x12\x14.nauthz.EventRequest\x1a\x12.nauthz.EventReply\"\x00B3Z1github.com/Buildtall-Systems/relay.nostr.io/protob\x06proto3"

var (
	file_proto_nauthz_proto_rawDescOnce sync.Once
	file_proto_nauthz_proto_rawDescData []byte
)

func file_proto_nauthz_proto_rawDescGZIP() []byte {
	file_proto_nauthz_proto_rawDescOnce.Do(func() {
		file_proto_nauthz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_nauthz_proto_rawDesc), len(file_proto_nauthz_proto_rawDesc)))
	})
	return file_proto_nauthz_proto_rawDescData
}

var file_proto_nauthz_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_nauthz_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_nauthz_proto_goTypes = []any{
	(Decision)(0),                  // 0: nauthz.Decision
	(*Event)(nil),                  // 1: nauthz.Event
	(*EventRequest)(nil),           // 2: nauthz.EventRequest
	(*EventReply)(nil),             // 3: nauthz.EventReply
	(*Event_TagEntry)(nil),         // 4: nauthz.Event.TagEntry
	(*EventRequest_Nip05Name)(nil), // 5: nauthz.EventRequest.Nip05Name
}
var file_proto_nauthz_proto_depIdxs = []int32{
	4, // 0: nauthz.Event.tags:type_name -> nauthz.Event.TagEntry
	1, // 1: nauthz.EventRequest.event:type_name -> nauthz.Event
	5, // 2: nauthz.EventRequest.nip05:type_name -> nauthz.EventRequest.Nip05Name
	0, // 3: nauthz.EventReply.decision:type_name -> nauthz.Decision
	2, // 4: nauthz.Authorization.EventAdmit:input_type -> nauthz.EventRequest
	3, // 5: nauthz.Authorization.EventAdmit:output_type -> nauthz.EventReply
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_nauthz_proto_init() }
func file_proto_nauthz_proto_init() {
	if File_proto_nauthz_proto != nil {
		return
	}
	file_proto_nauthz_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_nauthz_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_nauthz_proto_rawDesc), len(file_proto_nauthz_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_nauthz_proto_goTypes,
		DependencyIndexes: file_proto_nauthz_proto_depIdxs,
		EnumInfos:         file_proto_nauthz_proto_enumTypes,
		MessageInfos:      file_proto_nauthz_proto_msgTypes,
	}.Build()
	File_proto_nauthz_proto = out.File
	file_proto_nauthz_proto_goTypes = nil
	file_proto_nauthz_proto_depIdxs = nil
}
